- name: Remove device
  hosts: cvp
  connection: local
  gather_facts: false

  vars:
    CVP_DEVICES:
      - serialNumber: s1-core1
        parentContainerName: ""
      - serialNumber: s1-core2
        parentContainerName: ""
      - serialNumber: s1-brdr1
        parentContainerName: ""
      - serialNumber: s1-brdr2
        parentContainerName: ""
      - serialNumber: s1-leaf1
        parentContainerName: ""
      - serialNumber: s1-leaf2
        parentContainerName: ""
      - serialNumber: s1-leaf3
        parentContainerName: ""
      - serialNumber: s1-leaf4
        parentContainerName: ""
      - serialNumber: s1-spine1
        parentContainerName: ""
      - serialNumber: s1-spine2
        parentContainerName: ""
      - serialNumber: s1-host1
        parentContainerName: ""
      - serialNumber: s1-host2
        parentContainerName: ""
      - serialNumber: s2-core1
        parentContainerName: ""
      - serialNumber: s2-core2
        parentContainerName: ""
      - serialNumber: s2-brdr1
        parentContainerName: ""
      - serialNumber: s2-brdr2
        parentContainerName: ""
      - serialNumber: s2-leaf1
        parentContainerName: ""
      - serialNumber: s2-leaf2
        parentContainerName: ""
      - serialNumber: s2-leaf3
        parentContainerName: ""
      - serialNumber: s2-leaf4
        parentContainerName: ""
      - serialNumber: s2-spine1
        parentContainerName: ""
      - serialNumber: s2-spine2
        parentContainerName: ""
      - serialNumber: s2-host1
        parentContainerName: ""
      - serialNumber: s2-host2
        parentContainerName: ""

      # - fqdn: TelecomB-DV-1
      #   parentContainerName: ""
      # - fqdn: TelecomB-DV-2
      #   parentContainerName: ""
      # - fqdn: TelecomB-HOST-1
      #   parentContainerName: ""
      # - fqdn: TelecomB-HOST-2
      #   parentContainerName: ""

  tasks:

    - name: Import Global Vars
      ansible.builtin.include_vars: "{{ item }}"
      with_items:
        - "../global_vars/global_dc_vars.yml"

    - name: remove device
      arista.cvp.cv_device_v3:
          devices: '{{CVP_DEVICES}}'
          state: provisioning_reset